always-run:
  script: echo 'this should always run'
  
on-pull-requests:
  script: 
  - echo 'this should run on pull requests'
  - echo $CI_EXTERNAL_PULL_REQUEST_IID
  - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_SHA
  only:
    - external_pull_requests

except-pull-requests:
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests
