always-run:
  script: echo 'this should always run'
  except:
    refs:
      - branches
  
on-pull-requests:
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests

except-pull-requests:
  script: echo 'this should not run on pull requests'
  only:
    refs:
      - branches
